// Bundles only the icons the pages actually use into public/js/icons-local.js and registers them with
// the self-hosted iconify-icon element, so no icon is ever fetched from api.iconify.design at runtime.
const fs = require('fs');
const path = require('path');

const pub = path.join(__dirname, '..', 'public');
const sources = [path.join(pub, 'index.html'), path.join(pub, 'privacy.html'), path.join(pub, 'reset.html'), path.join(pub, 'stats.html')]
  .concat(fs.readdirSync(path.join(pub, 'js')).filter((f) => f.endsWith('.js') && f !== 'icons-local.js').map((f) => path.join(pub, 'js', f)));

// Icons whose names are assembled at runtime (e.g. solar:alt-arrow-${open ? 'up' : 'down'}-linear) cannot be
// found by scanning, so list every variant here.
const EXTRA = ['solar:alt-arrow-up-linear', 'solar:alt-arrow-down-linear'];

const used = new Set(EXTRA);
for (const f of sources) {
  if (!fs.existsSync(f)) continue;
  for (const m of fs.readFileSync(f, 'utf8').matchAll(/\b(solar|mdi):([a-z0-9-]+)/g)) {
    if (!m[2].endsWith('-')) used.add(`${m[1]}:${m[2]}`); // skip the stem of a runtime-built name
  }
}

const byPrefix = {};
for (const full of used) {
  const [prefix, name] = full.split(':');
  (byPrefix[prefix] = byPrefix[prefix] || []).push(name);
}

const collections = [];
const missing = [];
for (const [prefix, names] of Object.entries(byPrefix)) {
  const set = require(`@iconify-json/${prefix}/icons.json`);
  const out = { prefix, width: set.width || 24, height: set.height || 24, icons: {} };
  for (const name of names.sort()) {
    let icon = set.icons[name];
    if (!icon && set.aliases && set.aliases[name]) {
      const alias = set.aliases[name];
      const parent = set.icons[alias.parent];
      if (parent) icon = { ...parent, ...alias };
    }
    if (icon) {
      out.icons[name] = icon;
    } else {
      // Not in the icon set (it is already blank on the live site). Register an empty icon so the
      // browser does not go to the network looking for it.
      out.icons[name] = { body: '' };
      missing.push(`${prefix}:${name}`);
    }
  }
  collections.push(out);
}

if (missing.length) console.warn('not in the icon sets, registered as blank:', missing.join(', '));

const body = `// GENERATED by tools/build-icons.js — do not edit. ${used.size} icons.\n` +
  `(function () {\n  var C = window.customElements && window.customElements.get('iconify-icon');\n  if (!C || !C.addCollection) return;\n` +
  collections.map((c) => `  C.addCollection(${JSON.stringify(c)});`).join('\n') + '\n})();\n';
fs.writeFileSync(path.join(pub, 'js', 'icons-local.js'), body);
console.log(`wrote public/js/icons-local.js (${used.size} icons, ${(body.length / 1024).toFixed(1)} KB)`);
